<?xml version="1.0"?>
<project
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <modelVersion>4.0.0</modelVersion>
  <artifactId>dal.jooq</artifactId>
  <version>1.0-SNAPSHOT</version>
  <name>dal.jooq</name>

  <properties>
    <jooq.configuration.path>src/main/resources/jooq.configuration.xml</jooq.configuration.path>
    <skip.jooq.generation>true</skip.jooq.generation>
  </properties>

  <!-- mvn clean generate-sources -Ddatabase.url=jdbc:postgresql://127.0.0.1:5432/carrental -Ddatabase.user=twinkle_user -Ddatabase.password=Sr412Tqew! -X -->

  <parent>
    <artifactId>root</artifactId>
    <groupId>com.github.donkeyrit.twinkle</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <dependencies>
    <dependency>
        <groupId>org.jooq</groupId>
        <artifactId>jooq</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>

        <executions>
          <execution>
            <id>jooq-codegen</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>

        <configuration>
          <skip>${skip.jooq.generation}</skip>
          <configurationFile>${jooq.configuration.path}</configurationFile>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
