persistence.strategy=hibernate
# or
#persistence.strategy=jooq

# Database Connection String
database.url=jdbc:postgresql://localhost:5432/yourdatabase
database.user=youruser
database.password=yourpassword
