version: '3.8'
services:
  postgres_local:
    image: postgres:latest
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: carrent
    ports:
      - "5432:5432"
    volumes:
      - local_db_data:/var/lib/postgresql

  postgres_local_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: twinkle_test_user
      POSTGRES_PASSWORD: Sr412Tqew!
      POSTGRES_DB: integration_tests_carrental
    ports:
      - "5433:5432"
    volumes:
      - local_db_test_data:/var/lib/postgresql

volumes:
  local_db_data:
  local_db_test_data:

